Models/User.cs
using MeetUp.Data;
using System.ComponentModel.DataAnnotations;

namespace MeetUp.Models
{

    public class User
    {
        [Key]
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Role Role { get; set; }
        public ICollection<MeetActivity>? MyActivities{ get; set; }
        public ICollection<UserActivity>? MyUserActivities{ get; set; }
        public ICollection<Rating>? Ratings { get; set; }
    }
}

Controllers/RatingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MeetUp.Data;
using MeetUp.Models;
using MeetUp.Interfaces;
using Microsoft.AspNetCore.Authorization;
using MeetUp.ViewModels;

namespace MeetUp.Controllers
{
    public class RatingsController : Controller
    {
        private readonly IRatingService service;
        private readonly IUserService userService;

        public RatingsController(IRatingService _service, IUserService _userService)
        {
            service = _service;
            userService = _userService;
        }

        public async Task<IActionResult> Index()
        {
            var ratings = await service.GetAll();
            return View(ratings);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rating = service.GetById(id.Value);
            if (rating == null)
            {
                return NotFound();
            }

            return View(rating);
        }

        public IActionResult Create()
        {
            ViewData["RevieweeId"] = new SelectList(userService.GetAll().Result, "Id", "UserName");
            return View();
        }
        [HttpGet]
        public IActionResult AddRating(string id)
        {
         
            AddRatingViewModel rating = new AddRatingViewModel
            {
                Id = id,
            };
           
            return View(rating);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddRatingPost([Bind("Score,Message,Id")] AddRatingViewModel newRating)
        {
         
            if (ModelState.IsValid)
            {
                var rating = new Rating
                {
                    Score = newRating.Score.Value,
                    Message = newRating.Message,
                    RevieweeId = newRating.Id

                };
               
                var result = service.Add(rating);
                return RedirectToAction("Details", "Users", new { id = newRating.Id });
            }
            
            return RedirectToAction("Details", "Users" 
                ,new { id= newRating.Id });
        }

        [HttpPost]
        [Authorize(Roles = UserRoles.Admin)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Score,Message,RevieweeId")] Rating rating)
        {
            if (ModelState.IsValid)
            {
                var result = service.Add(rating);
                return RedirectToAction(nameof(Index));
            }
            ViewData["RevieweeId"] = new SelectList(userService.GetAll().Result, "Id", "UserName", rating.RevieweeId);
            return View(rating);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rating = await service.GetById(id);
            if (rating == null)
            {
                return NotFound();
            }
            ViewData["RevieweeId"] = new SelectList(userService.GetAll().Result, "Id", "UserName", rating.RevieweeId);
            return View(rating);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Score,Message,RevieweeId")] Rating rating)
        {
            if (id != rating.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                service.Update(rating);
            }
      
            ViewData["RevieweeId"] = new SelectList(userService.GetAll().Result, "Id", "Id", rating.RevieweeId);
            return View(rating);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null )
            {
                return NotFound();
            }

            var rating = await service.GetById(id);
            if (rating == null)
            {
                return NotFound();
            }

            return View(rating);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var rating = await service.GetById(id);
            if (rating != null)
            {
                service.Delete(rating);
            }  
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/UsersController.cs
using MeetUp.Data;
using MeetUp.Interfaces;
using MeetUp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace MeetUp.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserService service;

        public UsersController(IUserService _service)
        {
            service = _service;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            var users = await service.GetAll();
            return users != null ?
                        View(users) :
                        Problem("Entity set 'MeetUpContext.User'  is null.");
        }
        
        // GET: Users/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await service.GetUserDetails(id);
            if (result == null)
            {
                return NotFound();
            }

            return View(result);
        }
        [Authorize(Roles = UserRoles.Admin)]
        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Create([Bind("Id,FullName,Email,Password")] AppUser user)
        { 
            if (ModelState.IsValid)
            {
                //user.Role = Role.USER;
                service.Add(user);
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }
        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Edit(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await service.GetById(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,Email,Password,Image")] AppUser user)
        {


            if (ModelState.IsValid)
            {

                service.Update(user);

            }
            return View(user);
        }

        // GET: Users/Delete/5
        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Delete(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await service.GetById(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await service.GetById(id);
            if (user != null)
            {
                service.Delete(user);
            }

            return RedirectToAction(nameof(Index));
        }

    }
}

Views/Users/Create.cshtml
@model MeetUp.Models.AppUser

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
         @*   <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input type="password" asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>*@
           
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Users/Delete.cshtml
@model MeetUp.Models.AppUser

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
       @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>*@
     
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Users/Details.cshtml
@using Microsoft.AspNet.Identity;
@model MeetUp.ViewModels.UserDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<div>
    <h4>@Html.DisplayFor(model => model.User.Email)</h4>
    @if (Model.AverageScore == double.NaN || Model.AverageScore == 0)
    {
        <p>No reviews</p>
    }
    else
    {
        <p>
           Average rating: @Html.DisplayFor(model=> model.AverageScore)
        </p>
    }
    @if (User.Identity.IsAuthenticated && User.Identity.GetUserId() != Model.User.Id)
    {
        <a class="btn btn-primary" asp-controller="Ratings"
                       asp-action="AddRating"
                       asp-route-id="@Model.User.Id">Add review</a>
    }
    <hr />

</div>


<div class="d-flex w-100 ">
    <div class="w-50">
        <h4>Ratings</h4>
        @if (Model.Ratings.Count > 0)
        {
            
            @foreach (var item in Model.Ratings)
            {
                <div class="w-50 mb-1 p-2 border border-2 border-primary">
                    Score:  @Html.DisplayFor(modelItem => item.Score)  <br>
                    @Html.DisplayFor(modelItem => item.Message)
                </div>
               
            }
           
        }
        else
        {
            <p>No reviews</p>
        }
    </div>
    <div class="w-50">
        <h4>Activities</h4>
        @if (Model.UserActivities.Count > 0)
        {
            @foreach (var item in Model.UserActivities)
            {

                <div class="w-50 mb-1 p-2 border border-1 border-primary rounded">
                    <a asp-controller="MeetActivities"
                       asp-action="Details"
                       asp-route-id="@item.Activity.Id">
                        @Html.DisplayFor(modelItem => item.Activity.Name)</a> <br>
                    @Html.DisplayFor(modelItem => item.Activity.Time)
                </div>
            }
        }
        else
        {
            <p>No activities</p>
        }
    </div>

</div>


@if (User.IsInRole("admin"))
{
    <div>
        <a asp-action="Edit" asp-route-id="@Model?.User.Id">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>
}

Views/Users/Edit.cshtml
@model MeetUp.Models.AppUser

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
           @* <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>*@
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Users/Index.cshtml
@model IEnumerable<MeetUp.Models.AppUser>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
           @* <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>*@
           
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
           @* <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>*@
           
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>